INFORMACION PELICULAS
zrock-dev/Project_X pull request #45
Opened 2022-03-20 19:03 UTC by TheLocoto

Para esta base de datos me di cuenta que cambiando la cartelera de cada sala por un ArrayList<Peliculas> y ajustando otras funciones, tendriamos acceso a las peliculas de la sala con todos sus datos.
Luego en utils cree una funcion que me muestre la listadepeliculas (solo nombre) de la sala q queramos

2022-03-20 19:31 UTC, TheLocoto commented
Osea nuestro map seria en este cado el ArrayList<Peliculas> de cada sala, y dentro de este estarian todos los datos de las peliculas (nombre, descripcion, etc etc) y nombrando a la sala.cartelera tendriamos acceso a la lista de peliculas con sus datos

2022-03-21 04:23 UTC, zrock-dev requested changes

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/Sala.java
>          switch (capacidadAsientos) {
Cambiale el nombre a esta funcion, relacionado con lo que hace, clasificar peliculas por su calificacion.

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/Utils.java
> +    public static ArrayList<String> listaPeliculas(Sala sala){
que el nombre de la funcion sea mas claro

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/BaseDeDatos.java
> +    public static ArrayList<Pelicula> listaPeliculas() {
![image](https://user-images.githubusercontent.com/64939916/159204840-fd209814-187f-49c1-bad1-339e18d40d2f.png)

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/BaseDeDatos.java
> +                "un fesival de veraano que se celebra cada 90 años en una aldea remota de Suecia ", 7);
```suggestion
                "un fesival de verano que se celebra cada 90 años en una aldea remota de Suecia ", 7);
```

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/BaseDeDatos.java
> +                "de fantasia oscura, basada en el manga de Jujutsu Kaisen,creado por Gege AKutami",10);
```suggestion
                "de fantasia oscura, basada en el manga de Jujutsu Kaisen,creado por Gege AKutami", 10);
```

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/BaseDeDatos.java
> +                "seran convertidos en el animal que ellos escojan",7);
```suggestion
                "seran convertidos en el animal que ellos escojan", 7);
```

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/BaseDeDatos.java
> +                "lo ayuden a covertirse un emoji de una cara al igual que todos sus amigos, durante su aventura recorren varias aplicasiones y descubren que " +
```suggestion
                "lo ayuden a covertirse un emoji de una cara al igual que todos sus amigos, durante su aventura recorren varias aplicaciones y descubren que " +
```

2022-03-21 04:23 UTC, zrock-dev commented on src/Salas_de_video/BaseDeDatos.java
> +
Aqui comenta que se esta alimentando la base de datos.

2022-03-21 04:39 UTC, TheLocoto commented on src/Salas_de_video/Utils.java
> +    public static ArrayList<String> listaPeliculas(Sala sala){
El nombre esta claro, nos regresa la lista de peliculas de una sala (Claro solamente el nombre) Lo movi a la clase sala porque seria mas claro poner sala.listaPeliculas()

2022-03-21 04:41 UTC, zrock-dev commented on src/Salas_de_video/Utils.java
> +    public static ArrayList<String> listaPeliculas(Sala sala){
```suggestion
    public static ArrayList<String> getListaPeliculas(Sala sala){
```

Esta funcion tendria mas sentido en el `RoomsManager` por que este es el encargado de manejar las salas.

2022-03-21 04:41 UTC, TheLocoto commented on src/Salas_de_video/Sala.java
>          switch (capacidadAsientos) {
En si el nombre es el correcto, el que tiene ahora. Inserta la pelicula que le pasemos a la sala.

2022-03-21 04:43 UTC, zrock-dev commented on src/Salas_de_video/Sala.java
>          switch (capacidadAsientos) {
añadirPelicula, quizas...

2022-03-21 04:51 UTC, zrock-dev approved these changes

2022-03-21 04:52 UTC, merged