Como se hace un pull request?
zrock-dev/Project_X pull request #9
Opened 2022-03-16 20:18 UTC by TheLocoto

2022-03-16 20:27 UTC, zrock-dev commented
les muestro en  el review de hoy

2022-03-16 23:14 UTC, zrock-dev requested changes
Revisa la logica de los puntos y como afectan los descuentos a los puntos.
![image](https://user-images.githubusercontent.com/64939916/158701867-4180e067-94df-4b72-943d-bae80c56e0b0.png)

2022-03-16 23:14 UTC, zrock-dev commented on src/Boleto.java
>      }
```suggestion
```

2022-03-16 23:14 UTC, zrock-dev commented on src/Boleto.java
> +    public void aplicarDescuento(Boleteria.MetodoPago metodo,Semana dia,String tipoPelicula){
En esta funcion no es necesario clasificar el tipo de pelicula, la clase boleteria te pasa el precio clasificado de antemano. 
```suggestion
    public void aplicarDescuento(Boleteria.MetodoPago metodo,Semana dia){
```

2022-03-16 23:14 UTC, zrock-dev commented on src/Boleteria.java
> +        Boleto boleto = new Boleto(registroClientes.get(ci), precioPelicula, salaMap.get(codigoSala),"2D");
no es necesario pasarle  un tipoPelicula esta clase(Boleteria) tiene un metodo para determinar el precio de la pelicula.
![image](https://user-images.githubusercontent.com/64939916/158703951-0ee90050-3153-470d-b501-553d1c02c20a.png)
Es a esta funcion a la que se le pasa el tipo de pelicula.
Le pasamos al boleto el precio ya clasificado con`precioPelicula`

2022-03-16 23:14 UTC, zrock-dev commented on src/Boleto.java
> +                puntos = (40);
Cada entrada equivale a 50pts!

2022-03-16 23:14 UTC, zrock-dev commented on test/BoletoTest.java
> +public class BoletoTest {
Puedes hacer el test para que se generen los choques de descuentos?

2022-03-16 23:14 UTC, zrock-dev commented on test/BoletoTest.java
> +            boleto1.aplicarDescuento(Boleteria.MetodoPago.EFECTIVO,Semana.DOMINGO,boleto1.tipoPelicula);
```suggestion
            boleto1.aplicarDescuento(Boleteria.MetodoPago.EFECTIVO,Semana.Jueves,boleto1.tipoPelicula);
```

2022-03-16 23:23 UTC, TheLocoto commented on src/Boleto.java
> +                    puntos = (int) (40-(40 * .12));
No se obtiene el mismo resultado:
40*0.12 =0.8
40-40*0.12=35.2 

Estoy trabajando con los precios finales

2022-03-16 23:29 UTC, TheLocoto commented on src/Boleto.java
> +        double precio = 0;
al no darle el valor de 0 salta un error, y automaticamente agrega el = 0.

2022-03-16 23:30 UTC, TheLocoto commented on src/Boleto.java
> +            setPrecioPelicula(precio);
ok, lo acabo de arreglar.

2022-03-16 23:39 UTC, TheLocoto commented on src/Boleto.java
> +                puntos = (40);
perdon! no me fije bien ahora lo arreglo

2022-03-16 23:39 UTC, TheLocoto commented on test/BoletoTest.java
> +public class BoletoTest {
ahora lo hago y te mando

2022-03-16 23:40 UTC, zrock-dev commented on src/Boleto.java
> +        double precio = 0;
Sip,lo intente igual me aparecio.

2022-03-17 01:09 UTC, zrock-dev requested changes
Solo unos pequeños cambios, en general ya esta bien.

2022-03-17 01:09 UTC, zrock-dev commented on test/BoletoTest.java
> +            //3 CHOQUE UN MENOR DE EDAD QUE VE UNA ANIMACION UN DIA MIERCOLES
Todo esta bien, podrias separar los tipos de test con funciones dentro de tu test, en lugar de separarlos mediante comentarios.
```suggestion
        @Test
        public void testChoqueDeDescuentos(){
        }
```

2022-03-17 01:09 UTC, zrock-dev commented on src/Boleto.java
> +    setPuntosCliente(puntos);
Me parece que esta funcion esta por demas, (no le encuentro otros usos)
```suggestion
    cliente.sumarPuntos(puntos);
```

2022-03-17 03:20 UTC, zrock-dev approved these changes
Todo ok, excepto por ese directorio out. Pero ya vemos como lo sacamos.

2022-03-17 03:25 UTC, merged